name: Flujo de Trabajo Hola Mundo

# Controla cuándo se ejecutará el flujo de trabajo
on: [push]

# Un flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo
jobs:
  # Este flujo de trabajo contiene un solo trabajo llamado "saludar"
  greet:
    # El tipo de ejecutor en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo
    steps:
      # Verifica tu repositorio bajo $GITHUB_WORKSPACE, por lo que tu trabajo puede acceder a él
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      # Ejecuta un solo comando usando el shell del ejecutor
      - name: Ejecutar un script de una línea
        run: echo "Hola, Mundo!"